baseURL = "https://randomstr1ng.github.io/sap-security-wiki-hugo/"
languageCode = "en-us"
title = "SAP Security Wiki"
disableKinds = ["taxonomy", "taxonomyTerm"]

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"

[params]
  themeVariant = "blue"
  description = "A YAML-driven SAP Security Wiki"
