baseURL = 'https://randomstr1ng.github.io/github-pages-test/'
languageCode = 'en-us'
title = 'SAP Pentest Playbook'
theme = 'hugo-book'

[params]
BookTheme = 'auto'
BookToC = true
BookMenuBundle = '/content'
BookSection = '*'
