baseURL: "https://randomstr1ng.github.io/github-pages-test/"
languageCode: "en-us"
title: "SAP Security Wiki"
theme: "hugo-theme-docsy"
module:
  imports:
    - path: github.com/google/docsy
      disable: false
params:
  mainSections:
    - "Outside to SAP"
    - "Within SAP"
    - "From SAP to the Outside"
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - html
    - json
