baseURL = "https://randomstr1ng.github.io/github-pages-test/"
languageCode = "en-us"
title = "My Wiki"
theme = "hugo-geekdoc"
pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableRobotsTXT = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 1
endLevel = 9

[taxonomies]
tag = "tags"

[params]
geekdocToC = 3
geekdocLogo = "cbas_logo.png"
geekdocBackToTop = true
geekdocNextPrev = false
geekdocRepo = "https://github.com/randomstr1ng/github-pages-test"
geekdocEditPath = "edit/main"
geekdocPageLastmod = true
geekdocSearchShowParent = true

[params.geekdocContentLicense]
name = "CC BY-SA 4.0"
link = "https://creativecommons.org/licenses/by-sa/4.0/"
