baseURL = "https://randomstr1ng.github.io/github-pages-test/"
languageCode = "en-us"
title = "SAP Security Wiki"
relativeURLs = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "A YAML-driven SAP Security Wiki"
  author = "Your Name"
