name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js (for building theme assets)
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Theme Dependencies & Build Assets
        run: |
          cd themes/hugo-geekdoc
          npm install
          npm run build
          cd ../..

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.124.1"

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
